src/Entity/Profile.php
<?php

namespace App\Entity;

use App\Repository\ProfileRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProfileRepository::class)
 */
class Profile
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity=User::class, inversedBy="profile", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    /**
     * @ORM\Column(type="integer")
     */
    private $money;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getMoney(): ?int
    {
        return $this->money;
    }

    public function setMoney(int $money): self
    {
        $this->money = $money;

        return $this;
    }
    public function __toString(): string
    {
        return "id:" . $this->id . " modey:" . $this->money;
    }
}

templates/base.html.twig
{# templates/base.html.twig #}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>{% block title %}Welcome!{% endblock %}</title>
    <link
    />
    {% block stylesheets %}{% endblock %}
</head>
<body>
<nav>
    <a href="#">Автомагазин</a>
    <ul>
        {% if app.user %}
            <li><a href="{{ path('app_logout') }}">Logout</a></li>
        {% else %}
            <li><a href="{{ path('app_login') }}">Login</a></li>
            <li><a href="{{ path('registration') }}">Registration</a></li>
        {% endif %}
    </ul>
</nav>
{% block body %}{% endblock %}{% block javascripts %}{% endblock %}
</body>
</html>